### ISSUE TITLE
the imagenet100 dataset

### ISSUE THREAD

**Issue by cheliu-computation** [Sherrylone/Zero-CL#1]
Hi, Thanks for your impressive work and comprensive code

The CIFAR scripts work well, but the ImageNet100/ImageNet experiments seems lack of some code.
In ImageNet-100/main.py, the dataset is not working with imagenet100,
In ImageNet-100/evaluate.py, the code has no dataset for imagenet100 as well

**Comment by Sherrylone** [comment]
Hi, thanks for your attention to our work!
The problem may be caused by the different dataset structures between the cluster of the company and yours.
As in our cluster, the training set is {nxxxx01/xxxx01.jpg, ....,nxxxx02/xxxx01.jpg}, while the validation dataset is not in the ImageFolder structure. You can simply modify the Dataset class in the code to ImageFolder style. Besides, the imagenet100 classes index is here (https://github.com/Sherrylone/Align-Representation-with-Base/issues/1).
